.TH "bankapp.server.IBManager" 3 "Wed May 17 2017" "BankApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bankapp.server.IBManager \- Interface \fBIBManager\fP extends Remote to set function names and params\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Remote\&.
.PP
Inherited by \fBbankapp\&.server\&.BManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBlogin\fP (String user, String pass)  throws RemoteException"
.br
.RI "function name and params "
.in -1c
.SH "Detailed Description"
.PP 
Interface \fBIBManager\fP extends Remote to set function names and params\&. 


.PP
\fBAuthor:\fP
.RS 4
BICHRI 
.RE
.PP
\fBDate:\fP
.RS 4
05-17-2017 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "boolean bankapp\&.server\&.IBManager\&.login (String user, String pass) throws RemoteException"

.PP
function name and params 
.PP
\fBParameters:\fP
.RS 4
\fIuser\fP 
.br
\fIpass\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIRemoteException\fP 
.RE
.PP

.PP
Implemented in \fBbankapp\&.server\&.BManager\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BankApp from the source code\&.
