.TH "bankapp.server.ServerTest" 3 "Wed May 24 2017" "BankApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bankapp.server.ServerTest \- This is the \fBServerTest\fP class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetup\fP ()  throws RemoteException"
.br
.RI "initialise bankDAO , \fBBManager\fP "
.ti -1c
.RI "void \fBtestLogin\fP ()  throws RemoteException"
.br
.RI "Test login\&. "
.ti -1c
.RI "void \fBtestTransaction\fP ()  throws RemoteException"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static junit\&.framework\&.Test \fBsuite\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the \fBServerTest\fP class\&. 


.PP
\fBAuthor:\fP
.RS 4
BICHRI 
.RE
.PP
\fBDate:\fP
.RS 4
05-17-2017 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void bankapp\&.server\&.ServerTest\&.setup () throws RemoteException"

.PP
initialise bankDAO , \fBBManager\fP 
.PP
\fBExceptions:\fP
.RS 4
\fIRemoteException\fP 
.RE
.PP

.SS "void bankapp\&.server\&.ServerTest\&.testLogin () throws RemoteException"

.PP
Test login\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIRemoteException\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for BankApp from the source code\&.
