.TH "bankapp.client.UserWindow" 3 "Wed May 24 2017" "BankApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bankapp.client.UserWindow \- This is the \fBUserWindow\fP Class\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits JFrame\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUserWindow\fP (final \fBBankController\fP bc, String name)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.RI "Launch the application\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is the \fBUserWindow\fP Class\&. 


.PP
\fBAuthor:\fP
.RS 4
BICHRI
.RE
.PP
\fBDate:\fP
.RS 4
05-17-2017 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "bankapp\&.client\&.UserWindow\&.UserWindow (final \fBBankController\fP bc, String name)"

.PP
\fBParameters:\fP
.RS 4
\fIbc,name\fP Create the frame\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void bankapp\&.client\&.UserWindow\&.main (String [] args)\fC [static]\fP"

.PP
Launch the application\&. 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for BankApp from the source code\&.
