.TH "bankapp.server.bankAccountTest" 3 "Wed May 24 2017" "BankApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bankapp.server.bankAccountTest \- This is the \fBbankAccountTest\fP class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBvalidAccount\fP ()"
.br
.RI "create a valid account "
.in -1c
.SH "Detailed Description"
.PP 
This is the \fBbankAccountTest\fP class\&. 


.PP
\fBAuthor:\fP
.RS 4
BICHRI 
.RE
.PP
\fBDate:\fP
.RS 4
05-17-2017 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for BankApp from the source code\&.
