.TH "bankapp.server.UserTest" 3 "Wed May 24 2017" "BankApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bankapp.server.UserTest \- This is the \fBUserTest\fP class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBvalidUser\fP ()"
.br
.RI "create valid user "
.ti -1c
.RI "void \fBtestAddFunds\fP ()"
.br
.RI "test the add funds "
.ti -1c
.RI "void \fBtestTransaction\fP ()"
.br
.RI "test a transaction "
.in -1c
.SH "Detailed Description"
.PP 
This is the \fBUserTest\fP class\&. 


.PP
\fBAuthor:\fP
.RS 4
BICHRI 
.RE
.PP
\fBDate:\fP
.RS 4
05-17-2017 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for BankApp from the source code\&.
