.TH "bankapp.server.bankServer" 3 "Wed May 17 2017" "BankApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bankapp.server.bankServer \- This is the bank server Class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String args[])"
.br
.RI "main function that will do the server hundling "
.in -1c
.SH "Detailed Description"
.PP 
This is the bank server Class\&. 


.PP
\fBAuthor:\fP
.RS 4
BICHRI 
.RE
.PP
\fBDate:\fP
.RS 4
05-17-2017 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void bankapp\&.server\&.bankServer\&.main (String args[])\fC [static]\fP"

.PP
main function that will do the server hundling 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for BankApp from the source code\&.
