.TH "bankapp.server.User" 3 "Wed May 24 2017" "BankApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bankapp.server.User \- This is the \fBUser\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbankapp\&.server\&.Account\fP, and Serializable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUser\fP (String username, String pass, String email)"
.br
.RI "constractor "
.ti -1c
.RI "void \fBdeduceAccountFunds\fP (String accNum, long money)"
.br
.ti -1c
.RI "void \fBaddFundstoAccount\fP (String accNum, long money)"
.br
.ti -1c
.RI "int \fBcreateAccount\fP ()"
.br
.ti -1c
.RI "void \fBaddAccount\fP (\fBBankAccount\fP acc)"
.br
.ti -1c
.RI "String \fBgetEmail\fP ()"
.br
.ti -1c
.RI "void \fBsetEmail\fP (String email)"
.br
.ti -1c
.RI "void \fBdeleteAccount\fP (String accNum)"
.br
.ti -1c
.RI "\fBBankAccount\fP \fBgetAccount\fP (String accNum)"
.br
.ti -1c
.RI "HashMap< String, \fBBankAccount\fP > \fBgetAccounts\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the \fBUser\fP\&. 


.PP
\fBAuthor:\fP
.RS 4
BICHRI 
.RE
.PP
\fBDate:\fP
.RS 4
05-17-2017 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "bankapp\&.server\&.User\&.User (String username, String pass, String email)"

.PP
constractor 
.PP
\fBParameters:\fP
.RS 4
\fIusername\fP 
.br
\fIpass\fP 
.br
\fIemail\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for BankApp from the source code\&.
