.TH "bankapp.server.Account" 3 "Wed May 24 2017" "BankApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bankapp.server.Account \- This is the \fBAccount\fP Class\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBbankapp\&.server\&.Admin\fP, and \fBbankapp\&.server\&.User\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAccount\fP (String username, String pass)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "String \fBgetUsername\fP ()"
.br
.RI "get the user name "
.ti -1c
.RI "String \fBgetPass\fP ()"
.br
.RI "get the user password "
.ti -1c
.RI "void \fBsetPass\fP (String pass)"
.br
.RI "set the user password "
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the \fBAccount\fP Class\&. 


.PP
\fBAuthor:\fP
.RS 4
BICHRI 
.RE
.PP
\fBDate:\fP
.RS 4
05-17-2017 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "bankapp\&.server\&.Account\&.Account (String username, String pass)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIusername\fP 
.br
\fIpass\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String bankapp\&.server\&.Account\&.getPass ()"

.PP
get the user password 
.PP
\fBReturns:\fP
.RS 4
pass 
.RE
.PP

.SS "String bankapp\&.server\&.Account\&.getUsername ()"

.PP
get the user name 
.PP
\fBReturns:\fP
.RS 4
username 
.RE
.PP

.SS "void bankapp\&.server\&.Account\&.setPass (String pass)"

.PP
set the user password 
.PP
\fBParameters:\fP
.RS 4
\fIpass\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for BankApp from the source code\&.
