.TH "bankapp.server.bankDAO" 3 "Wed May 17 2017" "BankApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bankapp.server.bankDAO \- This is the bank DAO Class\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbankapp\&.server\&.IbankDAO\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbankDAO\fP ()"
.br
.RI "Constractore for class \fBbankDAO\fP\&. "
.ti -1c
.RI "\fBUser\fP \fBgetUser\fP (String username)"
.br
.RI "Function to get user identified by a username giving as a param\&. "
.ti -1c
.RI "void \fBstoreUser\fP (\fBUser\fP user)"
.br
.RI "Store a new user\&. "
.ti -1c
.RI "void \fBupdateUser\fP (\fBUser\fP user)"
.br
.RI "update a existing user "
.ti -1c
.RI "void \fBstoreAccount\fP (Account acc)"
.br
.RI "Store a new amount\&. "
.ti -1c
.RI "void \fBupdateAccount\fP (Account acc)"
.br
.RI "update an existing amount "
.in -1c
.SH "Detailed Description"
.PP 
This is the bank DAO Class\&. 


.PP
\fBAuthor:\fP
.RS 4
BICHRI 
.RE
.PP
\fBDate:\fP
.RS 4
05-17-2017 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBUser\fP bankapp\&.server\&.bankDAO\&.getUser (String username)"

.PP
Function to get user identified by a username giving as a param\&. 
.PP
\fBParameters:\fP
.RS 4
\fIusername\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
user 
.RE
.PP

.PP
Implements \fBbankapp\&.server\&.IbankDAO\fP\&.
.SS "void bankapp\&.server\&.bankDAO\&.storeAccount (Account acc)"

.PP
Store a new amount\&. 
.PP
\fBParameters:\fP
.RS 4
\fIacc\fP 
.RE
.PP

.PP
Implements \fBbankapp\&.server\&.IbankDAO\fP\&.
.SS "void bankapp\&.server\&.bankDAO\&.storeUser (\fBUser\fP user)"

.PP
Store a new user\&. 
.PP
\fBParameters:\fP
.RS 4
\fIuser\fP 
.RE
.PP

.PP
Implements \fBbankapp\&.server\&.IbankDAO\fP\&.
.SS "void bankapp\&.server\&.bankDAO\&.updateAccount (Account acc)"

.PP
update an existing amount 
.PP
\fBParameters:\fP
.RS 4
\fIacc\fP 
.RE
.PP

.PP
Implements \fBbankapp\&.server\&.IbankDAO\fP\&.
.SS "void bankapp\&.server\&.bankDAO\&.updateUser (\fBUser\fP user)"

.PP
update a existing user 
.PP
\fBParameters:\fP
.RS 4
\fIuser\fP 
.RE
.PP

.PP
Implements \fBbankapp\&.server\&.IbankDAO\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BankApp from the source code\&.
