.TH "bankapp.client.RMIServiceLocator" 3 "Wed May 24 2017" "BankApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bankapp.client.RMIServiceLocator \- This is the bank RMIServices hundler Class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetService\fP (String ip, String port, String serviceName)"
.br
.RI "set the service of an RMI "
.ti -1c
.RI "char \fBlogin\fP (String user, String pass)"
.br
.RI "Login to RMIService\&. "
.ti -1c
.RI "void \fBcreateUser\fP (String user, String pass, String email)"
.br
.RI "RMI create user method call\&. "
.ti -1c
.RI "void \fBtransaction\fP (String user1, String user2, long money, String accNum1, String accNum2)"
.br
.RI "RMI transaction method call\&. "
.ti -1c
.RI "int \fBcreateBankAccount\fP (String user)"
.br
.RI "RMI create bank account method call\&. "
.ti -1c
.RI "void \fBaddFunds\fP (String user, String accNum, long money)"
.br
.RI "RMI add funds method call\&. "
.ti -1c
.RI "void \fBdeleteBankAccount\fP (String user, String accNum1, String accNum2)"
.br
.RI "RMI delete bank account method call\&. "
.ti -1c
.RI "void \fBdeleteAccount\fP (String user)"
.br
.RI "RMI delete account method call\&. "
.ti -1c
.RI "\fBUser\fP \fBgetUser\fP (String user)"
.br
.ti -1c
.RI "ArrayList< \fBReport\fP > \fBgetReports\fP (int accNum)"
.br
.ti -1c
.RI "ArrayList< \fBUser\fP > \fBgetUsers\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the bank RMIServices hundler Class\&. 


.PP
\fBAuthor:\fP
.RS 4
BICHRI 
.RE
.PP
\fBDate:\fP
.RS 4
05-17-2017 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void bankapp\&.client\&.RMIServiceLocator\&.addFunds (String user, String accNum, long money)"

.PP
RMI add funds method call\&. 
.PP
\fBParameters:\fP
.RS 4
\fIuser\fP 
.br
\fIaccNum\fP 
.br
\fImoney\fP 
.RE
.PP

.SS "int bankapp\&.client\&.RMIServiceLocator\&.createBankAccount (String user)"

.PP
RMI create bank account method call\&. 
.PP
\fBParameters:\fP
.RS 4
\fIuser\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.SS "void bankapp\&.client\&.RMIServiceLocator\&.createUser (String user, String pass, String email)"

.PP
RMI create user method call\&. 
.PP
\fBParameters:\fP
.RS 4
\fIuser\fP 
.br
\fIpass\fP 
.br
\fIemail\fP 
.RE
.PP

.SS "void bankapp\&.client\&.RMIServiceLocator\&.deleteAccount (String user)"

.PP
RMI delete account method call\&. 
.PP
\fBParameters:\fP
.RS 4
\fIuser\fP 
.RE
.PP

.SS "void bankapp\&.client\&.RMIServiceLocator\&.deleteBankAccount (String user, String accNum1, String accNum2)"

.PP
RMI delete bank account method call\&. 
.PP
\fBParameters:\fP
.RS 4
\fIuser\fP 
.br
\fIaccNum\fP 
.br
\fIaccNum2\fP 
.RE
.PP

.SS "char bankapp\&.client\&.RMIServiceLocator\&.login (String user, String pass)"

.PP
Login to RMIService\&. 
.PP
\fBParameters:\fP
.RS 4
\fIuser\fP 
.br
\fIpass\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
char 
.RE
.PP

.SS "void bankapp\&.client\&.RMIServiceLocator\&.setService (String ip, String port, String serviceName)"

.PP
set the service of an RMI 
.PP
\fBParameters:\fP
.RS 4
\fIip\fP 
.br
\fIport\fP 
.br
\fIserviceName\fP 
.RE
.PP

.SS "void bankapp\&.client\&.RMIServiceLocator\&.transaction (String user1, String user2, long money, String accNum1, String accNum2)"

.PP
RMI transaction method call\&. 
.PP
\fBParameters:\fP
.RS 4
\fIuser1\fP 
.br
\fIuser2\fP 
.br
\fImoney\fP 
.br
\fIaccNum1\fP 
.br
\fIaccNum2\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for BankApp from the source code\&.
