.TH "bankapp.client.RMIServiceLocator" 3 "Wed May 17 2017" "BankApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bankapp.client.RMIServiceLocator \- This is the bank RMIServices hundler Class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetService\fP (String ip, String port, String serviceName)"
.br
.RI "set the service of an RMI "
.ti -1c
.RI "boolean \fBlogin\fP (String user, String pass)"
.br
.RI "Login to RMIService\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is the bank RMIServices hundler Class\&. 


.PP
\fBAuthor:\fP
.RS 4
BICHRI 
.RE
.PP
\fBDate:\fP
.RS 4
05-17-2017 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "boolean bankapp\&.client\&.RMIServiceLocator\&.login (String user, String pass)"

.PP
Login to RMIService\&. 
.PP
\fBParameters:\fP
.RS 4
\fIuser\fP 
.br
\fIpass\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
false 
.RE
.PP

.SS "void bankapp\&.client\&.RMIServiceLocator\&.setService (String ip, String port, String serviceName)"

.PP
set the service of an RMI 
.PP
\fBParameters:\fP
.RS 4
\fIip\fP 
.br
\fIport\fP 
.br
\fIserviceName\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for BankApp from the source code\&.
