.TH "bankapp.server.IBankDAO" 3 "Wed May 24 2017" "BankApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bankapp.server.IBankDAO \- Interface IbankDAO to set function names and params\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBbankapp\&.server\&.BankDAO\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAccount\fP \fBgetAccount\fP (String username)"
.br
.RI "function name and params "
.ti -1c
.RI "void \fBstoreAccount\fP (\fBAccount\fP acc)"
.br
.RI "function name and params "
.ti -1c
.RI "void \fBstoreReport\fP (\fBReport\fP rep)"
.br
.RI "function name and params "
.ti -1c
.RI "void \fBdeleteAccount\fP (String username)"
.br
.RI "function name and params "
.ti -1c
.RI "ArrayList< \fBReport\fP > \fBgetReports\fP (int accNum)"
.br
.ti -1c
.RI "ArrayList< \fBUser\fP > \fBgetUsers\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface IbankDAO to set function names and params\&. 


.PP
\fBAuthor:\fP
.RS 4
BICHRI 
.RE
.PP
\fBDate:\fP
.RS 4
05-17-2017 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void bankapp\&.server\&.IBankDAO\&.deleteAccount (String username)"

.PP
function name and params 
.PP
\fBParameters:\fP
.RS 4
\fIacc\fP 
.RE
.PP

.PP
Implemented in \fBbankapp\&.server\&.BankDAO\fP\&.
.SS "\fBAccount\fP bankapp\&.server\&.IBankDAO\&.getAccount (String username)"

.PP
function name and params 
.PP
\fBParameters:\fP
.RS 4
\fIusername\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBAccount\fP 
.RE
.PP

.PP
Implemented in \fBbankapp\&.server\&.BankDAO\fP\&.
.SS "void bankapp\&.server\&.IBankDAO\&.storeAccount (\fBAccount\fP acc)"

.PP
function name and params 
.PP
\fBParameters:\fP
.RS 4
\fIacc\fP 
.RE
.PP

.PP
Implemented in \fBbankapp\&.server\&.BankDAO\fP\&.
.SS "void bankapp\&.server\&.IBankDAO\&.storeReport (\fBReport\fP rep)"

.PP
function name and params 
.PP
\fBParameters:\fP
.RS 4
\fIrep\fP 
.RE
.PP

.PP
Implemented in \fBbankapp\&.server\&.BankDAO\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BankApp from the source code\&.
