.TH "bankapp.server.BankAccount" 3 "Wed May 24 2017" "BankApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bankapp.server.BankAccount \- This is the \fBBankAccount\fP Class implements Serializable\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Serializable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBankAccount\fP ()"
.br
.RI "Constructor\&. "
.ti -1c
.RI "int \fBgetnumAcc\fP ()"
.br
.RI "get the account number "
.ti -1c
.RI "long \fBgetmoney\fP ()"
.br
.RI "get the money amount "
.ti -1c
.RI "void \fBaddmoney\fP (long money)"
.br
.RI "add money to an account "
.ti -1c
.RI "void \fBdeducemoney\fP (long money)"
.br
.RI "deduce money to an account "
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the \fBBankAccount\fP Class implements Serializable\&. 


.PP
\fBAuthor:\fP
.RS 4
BICHRI 
.RE
.PP
\fBDate:\fP
.RS 4
05-17-2017 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void bankapp\&.server\&.BankAccount\&.addmoney (long money)"

.PP
add money to an account 
.PP
\fBParameters:\fP
.RS 4
\fImoney\fP 
.RE
.PP

.SS "void bankapp\&.server\&.BankAccount\&.deducemoney (long money)"

.PP
deduce money to an account 
.PP
\fBParameters:\fP
.RS 4
\fImoney\fP 
.RE
.PP

.SS "long bankapp\&.server\&.BankAccount\&.getmoney ()"

.PP
get the money amount 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "int bankapp\&.server\&.BankAccount\&.getnumAcc ()"

.PP
get the account number 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for BankApp from the source code\&.
