.TH "bankapp.server.IbankDAO" 3 "Wed May 17 2017" "BankApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bankapp.server.IbankDAO \- Interface \fBIbankDAO\fP to set function names and params\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBbankapp\&.server\&.bankDAO\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUser\fP \fBgetUser\fP (String username)"
.br
.RI "function name and params "
.ti -1c
.RI "void \fBstoreUser\fP (\fBUser\fP user)"
.br
.RI "function name and params "
.ti -1c
.RI "void \fBupdateUser\fP (\fBUser\fP user)"
.br
.RI "function name and params "
.ti -1c
.RI "void \fBstoreAccount\fP (Account acc)"
.br
.RI "function name and params "
.ti -1c
.RI "void \fBupdateAccount\fP (Account acc)"
.br
.RI "function name and params "
.in -1c
.SH "Detailed Description"
.PP 
Interface \fBIbankDAO\fP to set function names and params\&. 


.PP
\fBAuthor:\fP
.RS 4
BICHRI 
.RE
.PP
\fBDate:\fP
.RS 4
05-17-2017 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBUser\fP bankapp\&.server\&.IbankDAO\&.getUser (String username)"

.PP
function name and params 
.PP
\fBParameters:\fP
.RS 4
\fIusername\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
user 
.RE
.PP

.PP
Implemented in \fBbankapp\&.server\&.bankDAO\fP\&.
.SS "void bankapp\&.server\&.IbankDAO\&.storeAccount (Account acc)"

.PP
function name and params 
.PP
\fBParameters:\fP
.RS 4
\fIacc\fP 
.RE
.PP

.PP
Implemented in \fBbankapp\&.server\&.bankDAO\fP\&.
.SS "void bankapp\&.server\&.IbankDAO\&.storeUser (\fBUser\fP user)"

.PP
function name and params 
.PP
\fBParameters:\fP
.RS 4
\fIuser\fP 
.RE
.PP

.PP
Implemented in \fBbankapp\&.server\&.bankDAO\fP\&.
.SS "void bankapp\&.server\&.IbankDAO\&.updateAccount (Account acc)"

.PP
function name and params 
.PP
\fBParameters:\fP
.RS 4
\fIacc\fP 
.RE
.PP

.PP
Implemented in \fBbankapp\&.server\&.bankDAO\fP\&.
.SS "void bankapp\&.server\&.IbankDAO\&.updateUser (\fBUser\fP user)"

.PP
function name and params 
.PP
\fBParameters:\fP
.RS 4
\fIuser\fP 
.RE
.PP

.PP
Implemented in \fBbankapp\&.server\&.bankDAO\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BankApp from the source code\&.
