.TH "bankapp.server.IBManager" 3 "Wed May 24 2017" "BankApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bankapp.server.IBManager \- Interface \fBIBManager\fP extends Remote to set function names and params\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Remote\&.
.PP
Inherited by \fBbankapp\&.server\&.BManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "char \fBlogin\fP (String user, String pass)  throws RemoteException"
.br
.RI "function name and params "
.ti -1c
.RI "void \fBtransaction\fP (String user1, String user2, long money, String accNum1, String accNum2)  throws RemoteException"
.br
.ti -1c
.RI "int \fBcreateBankAccount\fP (String user)  throws RemoteException"
.br
.ti -1c
.RI "void \fBaddFunds\fP (String user, String accNum, long money)  throws RemoteException"
.br
.ti -1c
.RI "void \fBdeleteBankAccount\fP (String user, String accNum1, String accNum2)  throws RemoteException"
.br
.ti -1c
.RI "void \fBdeleteAccount\fP (String user)  throws RemoteException"
.br
.ti -1c
.RI "void \fBcreateUser\fP (String username, String pass, String email)  throws RemoteException"
.br
.ti -1c
.RI "\fBUser\fP \fBgetUser\fP (String user)  throws RemoteException"
.br
.ti -1c
.RI "ArrayList< \fBReport\fP > \fBgetReports\fP (int accNum)  throws RemoteException"
.br
.ti -1c
.RI "ArrayList< \fBUser\fP > \fBgetUsers\fP ()  throws RemoteException"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface \fBIBManager\fP extends Remote to set function names and params\&. 


.PP
\fBAuthor:\fP
.RS 4
BICHRI 
.RE
.PP
\fBDate:\fP
.RS 4
05-17-2017 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "char bankapp\&.server\&.IBManager\&.login (String user, String pass) throws RemoteException"

.PP
function name and params 
.PP
\fBParameters:\fP
.RS 4
\fIuser\fP 
.br
\fIpass\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIRemoteException\fP 
.RE
.PP

.PP
Implemented in \fBbankapp\&.server\&.BManager\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BankApp from the source code\&.
