.TH "bankapp.server.Report" 3 "Wed May 24 2017" "BankApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bankapp.server.Report \- This is the \fBReport\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Serializable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReport\fP (String user1, String user2, long money, String accNum1, String accNum2)"
.br
.RI "constractor "
.ti -1c
.RI "\fBReport\fP (String user1, String accNum1)"
.br
.RI "constractor 2 "
.ti -1c
.RI "\fBReport\fP (String user1, String accNum1, long money)"
.br
.RI "constractor 3 "
.ti -1c
.RI "char \fBgetReportType\fP ()"
.br
.RI "get the report type "
.ti -1c
.RI "String \fBgetUser1\fP ()"
.br
.RI "get the user number 1 "
.ti -1c
.RI "String \fBgetUser2\fP ()"
.br
.RI "get the user number 2 "
.ti -1c
.RI "String \fBgetAccNum1\fP ()"
.br
.RI "get account 1 number "
.ti -1c
.RI "String \fBgetAccNum2\fP ()"
.br
.RI "get account 2 number "
.ti -1c
.RI "int \fBgetId\fP ()"
.br
.RI "id "
.ti -1c
.RI "long \fBgetMoney\fP ()"
.br
.RI "get money amount "
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the \fBReport\fP\&. 


.PP
\fBAuthor:\fP
.RS 4
BICHRI 
.RE
.PP
\fBDate:\fP
.RS 4
05-17-2017 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "bankapp\&.server\&.Report\&.Report (String user1, String user2, long money, String accNum1, String accNum2)"

.PP
constractor 
.PP
\fBParameters:\fP
.RS 4
\fIuser1\fP 
.br
\fIuser2\fP 
.br
\fImoney\fP 
.br
\fIaccNum1\fP 
.br
\fIaccNum2\fP 
.RE
.PP

.SS "bankapp\&.server\&.Report\&.Report (String user1, String accNum1)"

.PP
constractor 2 
.PP
\fBParameters:\fP
.RS 4
\fIuser1\fP 
.RE
.PP

.SS "bankapp\&.server\&.Report\&.Report (String user1, String accNum1, long money)"

.PP
constractor 3 
.PP
\fBParameters:\fP
.RS 4
\fIuser1\fP 
.br
\fIaccNum1\fP 
.br
\fImoney\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String bankapp\&.server\&.Report\&.getAccNum1 ()"

.PP
get account 1 number 
.PP
\fBReturns:\fP
.RS 4
accNum1 
.RE
.PP

.SS "String bankapp\&.server\&.Report\&.getAccNum2 ()"

.PP
get account 2 number 
.PP
\fBReturns:\fP
.RS 4
accNum2 
.RE
.PP

.SS "int bankapp\&.server\&.Report\&.getId ()"

.PP
id 
.PP
\fBReturns:\fP
.RS 4
id 
.RE
.PP

.SS "long bankapp\&.server\&.Report\&.getMoney ()"

.PP
get money amount 
.PP
\fBReturns:\fP
.RS 4
money 
.RE
.PP

.SS "char bankapp\&.server\&.Report\&.getReportType ()"

.PP
get the report type 
.PP
\fBReturns:\fP
.RS 4
reportType 
.RE
.PP

.SS "String bankapp\&.server\&.Report\&.getUser1 ()"

.PP
get the user number 1 
.PP
\fBReturns:\fP
.RS 4
user1 
.RE
.PP

.SS "String bankapp\&.server\&.Report\&.getUser2 ()"

.PP
get the user number 2 
.PP
\fBReturns:\fP
.RS 4
user2 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for BankApp from the source code\&.
