.TH "bankapp.server.Performance" 3 "Wed May 24 2017" "BankApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bankapp.server.Performance \- This is the \fBPerformance\fP class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.RI "initialise user and create an account , add funds and deduce account funds "
.in -1c
.SH "Detailed Description"
.PP 
This is the \fBPerformance\fP class\&. 


.PP
\fBAuthor:\fP
.RS 4
BICHRI 
.RE
.PP
\fBDate:\fP
.RS 4
05-17-2017 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void bankapp\&.server\&.Performance\&.main (String [] args)\fC [static]\fP"

.PP
initialise user and create an account , add funds and deduce account funds 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for BankApp from the source code\&.
