.TH "bankapp.server.User" 3 "Wed May 17 2017" "BankApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bankapp.server.User \- class \fBUser\fP contain the attributes that a user must have  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUser\fP (String username, String pass, String email)"
.br
.RI "Constractor for class \fBUser\fP\&. "
.ti -1c
.RI "String \fBgetUsername\fP ()"
.br
.RI "function to get the user name "
.ti -1c
.RI "void \fBsetUsername\fP (String username)"
.br
.RI "functionto set the user name "
.ti -1c
.RI "String \fBgetPass\fP ()"
.br
.RI "function to get the user password "
.ti -1c
.RI "void \fBsetPass\fP (String pass)"
.br
.RI "function to set the user password "
.ti -1c
.RI "String \fBgetEmail\fP ()"
.br
.RI "function to get the user email "
.ti -1c
.RI "void \fBsetEmail\fP (String email)"
.br
.RI "function to set the user email "
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.RI "function to get the user name "
.in -1c
.SH "Detailed Description"
.PP 
class \fBUser\fP contain the attributes that a user must have 


.PP
\fBAuthor:\fP
.RS 4
BICHRI 
.RE
.PP
\fBDate:\fP
.RS 4
05-17-2017 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "bankapp\&.server\&.User\&.User (String username, String pass, String email)"

.PP
Constractor for class \fBUser\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIusername\fP 
.br
\fIpass\fP 
.br
\fIemail\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String bankapp\&.server\&.User\&.getEmail ()"

.PP
function to get the user email 
.PP
\fBReturns:\fP
.RS 4
email 
.RE
.PP

.SS "String bankapp\&.server\&.User\&.getPass ()"

.PP
function to get the user password 
.PP
\fBReturns:\fP
.RS 4
pass 
.RE
.PP

.SS "String bankapp\&.server\&.User\&.getUsername ()"

.PP
function to get the user name 
.PP
\fBReturns:\fP
.RS 4
username 
.RE
.PP

.SS "void bankapp\&.server\&.User\&.setEmail (String email)"

.PP
function to set the user email 
.PP
\fBParameters:\fP
.RS 4
\fIemail\fP 
.RE
.PP

.SS "void bankapp\&.server\&.User\&.setPass (String pass)"

.PP
function to set the user password 
.PP
\fBParameters:\fP
.RS 4
\fIpass\fP 
.RE
.PP

.SS "void bankapp\&.server\&.User\&.setUsername (String username)"

.PP
functionto set the user name 
.PP
\fBParameters:\fP
.RS 4
\fIusername\fP 
.RE
.PP

.SS "String bankapp\&.server\&.User\&.toString ()"

.PP
function to get the user name 
.PP
\fBReturns:\fP
.RS 4
username 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for BankApp from the source code\&.
