.TH "bankapp.client.bankController" 3 "Wed May 17 2017" "BankApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bankapp.client.bankController \- This is the bank controller and hundler Class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbankController\fP (String ip, String port, String serviceName)"
.br
.RI "Constructor set the service for the RMI\&. "
.ti -1c
.RI "boolean \fBlogin\fP (String user, String pass)"
.br
.RI "Login Function Allow or Deny access to the application\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is the bank controller and hundler Class\&. 


.PP
\fBAuthor:\fP
.RS 4
BICHRI 
.RE
.PP
\fBDate:\fP
.RS 4
05-17-2017 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "bankapp\&.client\&.bankController\&.bankController (String ip, String port, String serviceName)"

.PP
Constructor set the service for the RMI\&. 
.PP
\fBParameters:\fP
.RS 4
\fIip\fP 
.br
\fIport\fP 
.br
\fIserviceName\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "boolean bankapp\&.client\&.bankController\&.login (String user, String pass)"

.PP
Login Function Allow or Deny access to the application\&. 
.PP
\fBParameters:\fP
.RS 4
\fIuser\fP 
.br
\fIpass\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
true 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for BankApp from the source code\&.
